import Link from "next/link";
import { searchMedicalRecords } from "@/features/search/data";
import { searchCategories, searchRequestSchema } from "@/features/search/model";

const categoryLabels: Record<string, string> = { all: "All", documents: "Documents", text: "Text blocks", labs: "Labs", medications: "Medications", diagnoses: "Diagnoses", allergies: "Allergies", vitals: "Vitals", procedures: "Procedures", notes: "Doctor notes" };

export default async function SearchPage({ searchParams }: { searchParams: Promise<{ q?: string; category?: string }> }) {
  const raw = await searchParams;
  const parsed = searchRequestSchema.safeParse({ q: raw.q ?? "", category: raw.category ?? "all" });
  const request = parsed.success ? parsed.data : { q: "", category: "all" as const };
  const results = await searchMedicalRecords(request.q, request.category);
  return <main className="mx-auto max-w-5xl px-6 py-12"><header className="flex items-center justify-between gap-4"><div><p className="text-sm font-semibold tracking-widest text-teal-700">MEDMEMORY</p><h1 className="mt-2 text-3xl font-semibold">Search medical records</h1><p className="mt-2 text-slate-600">Find documents, source text, and reviewed medical facts.</p></div><Link className="rounded-lg border px-4 py-2" href="/dashboard">Dashboard</Link></header>
    <form className="mt-8 rounded-xl border border-slate-200 bg-white p-5"><label className="font-semibold">Search<input autoFocus className="mt-2 w-full rounded-lg border border-slate-300 px-4 py-3 font-normal" defaultValue={request.q} maxLength={80} name="q" placeholder="Try Hemoglobin, Metformin, or a document name" /></label><div className="mt-4 flex flex-wrap gap-2">{searchCategories.map((category) => <label className={`cursor-pointer rounded-full px-3 py-2 text-sm ${request.category === category ? "bg-teal-700 text-white" : "bg-slate-100"}`} key={category}><input className="sr-only" defaultChecked={request.category === category} name="category" type="radio" value={category} />{categoryLabels[category]}</label>)}</div><button className="mt-4 rounded-lg bg-teal-700 px-5 py-3 font-semibold text-white">Search</button></form>
    {!request.q ? <section className="mt-8 rounded-xl border border-dashed border-slate-300 p-8 text-center"><h2 className="font-semibold">Search your private archive</h2><p className="mt-2 text-slate-500">Enter a document name, medical term, medicine, result, or phrase from a record.</p></section> : <section className="mt-8"><h2 className="font-semibold">{results.length} result{results.length === 1 ? "" : "s"}</h2>{results.length ? <div className="mt-4 space-y-4">{results.map((result) => <article className="rounded-xl border border-slate-200 bg-white p-5" key={result.id}><div className="flex flex-wrap justify-between gap-3"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-teal-50 px-2 py-1 text-xs font-semibold capitalize text-teal-800">{categoryLabels[result.category]}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs capitalize">{result.reviewStatus.replace("_", " ")}</span>{result.confidence !== null ? <span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{result.confidence >= .8 ? "High" : result.confidence >= .5 ? "Medium" : "Low"} confidence</span> : null}</div><h3 className="mt-3 text-lg font-semibold">{result.title}</h3><p className="mt-1 text-sm text-slate-600">{result.snippet}</p><p className="mt-2 text-xs text-slate-500">Source: {result.documentName}{result.pageNumber ? ` · Page ${result.pageNumber}` : ""}</p></div>{result.date ? <time className="text-sm text-slate-500">{new Date(result.date).toLocaleDateString()}</time> : null}</div><div className="mt-4 flex gap-4 text-sm"><Link className="font-semibold text-teal-700" href={result.href}>Open record</Link>{result.sourceHref ? <Link className="font-semibold text-teal-700" href={result.sourceHref}>View source</Link> : null}</div></article>)}</div> : <div className="mt-4 rounded-xl border border-dashed border-slate-300 p-8 text-center text-slate-600">No records matched this search.</div>}</section>}
  </main>;
}
